### ISSUE TITLE
ViewController の TableView 部分を UITableViewController に分割する

### ISSUE THREAD

**Issue by ysk-tngc** [MachonglishproK/SkillCheckProject#8]
# Context

Repository クラスの整理が終わったら取り組みましょう。

* TableView 部分を UITableViewController のサブクラスとして切り出す
* `ViewController` に `ContainerView` (UIView) を用意し、その中に `UITableViewController` のサブクラスを配置する

**Comment by MachonglishproK** [comment]
#17　にて本件対応済のため、クローズします。
